version: '2'
services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
